# ----------------------- #
#         Site            #
# ----------------------- #
title:       Ryan Oglesby
# email:       ryan.oglesby08@gmail.com
author:      Ryan Oglesby
description: "My thoughts and experiences as I navigate the world of Agile software development."
baseurl:     ""
url:         "http://ryanogles.by"
date_format: "%b %-d, %Y"

# ----------------------- #
#        Jekyll           #
# ----------------------- #
source:       source
excerpt_separator: "<!-- more -->"
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    date
paginate:     4
sass:
  compressed: true
gems:
  - octopress-image-tag
  - octopress-codeblock
  - octopress-codefence
  - octopress-solarized
  - octopress-gist
  - octopress-include-tag
  - jekyll-paginate
  - jekyll-sitemap
# https://github.com/jekyll/jekyll/issues/2938
exclude: [vendor]

# ----------------------- #
#    Google Services      #
# ----------------------- #
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics: UA-51481422-1
google_tag_manager:

# Bing services
bing_verification:

# ----------------------- #
#   Optional Features     #
# ----------------------- #
animated:             false
show_related_posts:   false
show_post_footers:    false
show_social_icons:    true
ajaxify_contact_form: false
enable_mathjax: false
extended_fonts: false
enable_anchorjs: false

# Facebook Page integration
# (for instant articles and other stuff)
fb_page: false
fb_page_id:

# ----------------------- #
#     Disqus Comments     #
# ----------------------- #
# (leave blank to disable Disqus)
disqus_shortname: ryanoglesby

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments:
facebook_appid:
facebook_comments_number: 10

# ----------------------- #
#      Social Icons       #
# ----------------------- #
github_username: ryanoglesby08
bitbucket_username:
stackoverflow_id:
twitter_username: ryanoglesby08
skype_username:
steam_nickname:
google_plus_id:
linkedin_username: ryanoglesby08
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# ----------------------- #
#   Post Sharing Icons    #
# ----------------------- #
show_sharing_icons: true
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: false
share_linkedin: true
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: true

# ----------------------- #
#          Text           #
# ----------------------- #
text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  share_buttons:
    text:         'Share me:'
    facebook:     'Share on Facebook'
    twitter:      'Share on Twitter'
    googleplus:   'Share on Google+'
    linkedin:     'Share on LinkedIn'
    digg:         'Share on Digg'
    tumblr:       'Share on Tumblr'
    reddit:       'Share on Reddit'
    stumbleupon:  'Share on StumbleUpon'
    hackernews:   'Share on Hacker News'
  post:
    updated:        'Updated'
    minute_read:    'minute read'
    related_posts:  'Related Posts'
  index:
    coming_soon: 'Coming soon...'
  contact:
    email:    'Email Address'
    content:  'What would you like to say?'
    subject:  'New submission!'
    submit:   'Say Hello'
    ajax:
      sending:  'sending..'
      sent:     'Message sent!'
      error:    'Error!'
  thanks: 'Thanks for contacting us. We will reply as soon as possible.'
  og_locale: 'en_US'
